import Head from 'next/head'
import Link from 'next/link';
import { gql } from "@apollo/client";
import client from "../../apollo-client";
import Layout from '../../components/layout'
import IndexRow from './IndexRow';

//
export default function TodoIndex(props) {
//  console.log(props.items.data);
  const data = props.items.data;
  const items = data.todos;
console.log(items);
  return (
  <Layout>
    <Head><meta name="description" content="Generated by create next app" />
    </Head>
    <div className="container">
      <Link href="/todos/create">
        <a className="btn btn-primary mt-2">New</a>
      </Link>      
      <div>
        <h1>Test2aa</h1>
        <hr />
        {items.map((item ,index) => {
          return (
            <IndexRow key={index} id={item.id} title={item.title} />
          )
        })}        
        </div>
    </div>
  </Layout>
  )
}
/* getServerSideProps */
export async function getServerSideProps({ params }) {
  const data = await client.query({
    query: gql`
    query {
      todos {
        id
        title
      }
    }
    `,
    fetchPolicy: "network-only"
  });
//console.log(data);   
  return {
      props: { items: data },
  }
}

