import Head from 'next/head'
import Link from 'next/link';
import Layout from '../components/layout'
import { gql } from "@apollo/client";
import client from "../apollo-client";

//
export default function Test2(props) {
//  console.log(props.items.data);
  const data = props.items.data;
  const items = data.todos;
console.log(items);
  return (
  <Layout>
    <div className="">
      <Head><meta name="description" content="Generated by create next app" />
      </Head>
       
      <div>
        <h1>Test2aa</h1>
        <hr />
        {items.map((item ,index) => ( 
          item.id
        ))}        
      </div>
    </div>
  </Layout>
  )
}
/* getServerSideProps */
export async function getServerSideProps({ params }) {
  const data = await client.query({
    query: gql`
    query {
      todos {
        id
        title
      }
    }
    ` 
  });
//console.log(data);   
  return {
      props: { items: data },
  }
}

